DROP TABLE IF EXISTS book;

CREATE TABLE book (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    publish_date DATE DEFAULT CURRENT_DATE
);